### ISSUE TITLE
Add github page

### ISSUE THREAD

**Issue by gustavakerstrom** [Karlkorv/best-song#18]
https://pages.github.com/
Vi måste spara user-secrets online mha typ azure key vault https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0

**Comment by Karlkorv** [comment]
Detta kräver att vi kommer på ett bättre namn än "best song" lmfao

**Comment by Karlkorv** [comment]
Går inte då vi har en serverside, github hostar bara static pages :(
